---

- name: create a scaleway server
  scaleway_compute:
    name: ansible_server
    state: running
    image: ec8b431e-ad39-4523-8b94-f3fa7f3cbd06
    organization: 43a3b6c8-916f-477b-b7ec-ff1898f5fdd9
    region: par1
    commercial_type: VC1S
    tags:
      - ansible
