---
- name: Install nginx daemon
  apt:
    name: nginx 
    state: present 
    update_cache: yes

- name: Start nginx and enable it at boot
  systemd:
    name: nginx 
    state: started
    enabled: yes
