---
- name: restart php-fpm
  systemd: 
    name: php7.0-fpm 
    state: restarted
  listen: restart php-fpm
  
- name: restart nginx
  systemd: 
    name: nginx
    state: restarted
  listen: restart nginx